# Generated by Django 2.0.3 on 2018-05-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='datatime',
            new_name='datetime',
        ),
    ]
